name: HACS Action

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  hacs:
    name: HACS Action
    runs-on: "ubuntu-latest"
    steps:
      - name: Format code with Prettier
        run: yarn prettier --write .  
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "plugin"
          
