name: 'Prepare release'

on: [push, pull_request]

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
         node-version: 20
 

      - name: Install
        run: |
          yarn install
      - name: Format code with Prettier
        run: yarn prettier --write .   
    
      - name: Build
        run: |
          
          
          yarn build
      - name: List build directory
        run: ls -R dist

      - name: Verify build file exists
        run: test -f dist/atomic-calendar-revive.js

      - name: Create a tag
        id: create_tag
        run: |
          TAG_NAME=v$(date +'%Y%m%d%H%M%S')
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          file: dist/atomic-calendar-revive.js
          asset_name: atomic-calendar-revive.js
          tag: ${{ env.TAG_NAME }}
          overwrite: true

      - name: Run Semantic Release
        run: npx semantic-release --debug
        env:
         GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Verify HACS compliance
        uses: hacs/action@main
        with:
          category: plugin
