name: 'Prepare release'

on: [push, pull_request]

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
         node-version: 20
 

      - name: Install
        run: |
          yarn install
      - name: Format code with Prettier
        run: yarn prettier --write .   
    
      - name: Build
        run: |
          
          
          yarn build
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release

        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          file: /home/runner/work/custom-ha-calendar/custom-ha-calendar/dist/atomic-calendar-revive.js
          asset_name: atomic-calendar-revive.js
          tag: ${{ github.ref }}
          overwrite: true
      - name: Run Semantic Release
        run: npx semantic-release --debug
        env:
         GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Verify HACS compliance
        uses: hacs/action@main
        with:
          category: plugin
